name: thesis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.3.1
  - pytorch-cuda=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pip:
    - pytorch-lightning==2.1.0
    - tensorboard==2.14.1
    - git+https://github.com/huggingface/transformers.git # to ensure using StarCoder2, latest version of transformers
    - tabulate>=0.8.9
    - tqdm>=4.62.3
    - pillow>=8.0.1
    - notebook>=6.4.5
    - jupyterlab>=3.2.1
    - matplotlib>=3.4.3
    - seaborn>=0.11.2
    - ipywidgets>=7.6.5
    - codecarbon>=2.3
    - evalplus>=0.2.1
    - openai>=1.16.2
    - wget>=3.2
    - appdirs>=1.4.4
    - tempdir>=0.7.1
    - multipledispatch>=0.6.0
    - numpy>=1.21.2
    - termcolor>=1.1.0
    - fire>=0.4.0
    - tree_sitter_languages>=0.16.0
    - tree_sitter>=0.19.0
    - torch>=2.2
    - fire>=0.4.0
    - accelerate>=0.30.1
    - bitsandbytes>=0.43.1